import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles, LogIn, UserPlus, Globe, User, ChevronDown, Users as UsersIcon, Upload } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { useTranslation } from 'react-i18next';
import ModelComparison from '../components/ModelComparison';
import LanguageSelector from '../components/LanguageSelector';
import MixpanelTest from '../components/MixpanelTest';
import SidebarMenu from '../components/SidebarMenu';
import HomePageLoggedIn from './HomePageLoggedIn';
import LandingPage from './LandingPage';